In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.6'

In [4]:
my_list = [0, 1, 2, 3, 4, 5, 6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [5]:
type(my_list)

list

# List to array

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(5, 100, 10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [12]:
np.arange(20,10)

array([], dtype=int64)

In [13]:
np.arange(20, 10, -1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [14]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

## Parameter tuning

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Hyper parameter tuning

In [16]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.zeros((10,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((2, 3))

In [ ]:
# Fix the random sequence so the examples below repeat on a clean run.
np.random.seed(42)
np.random.rand(2, 3)

In [ ]:
np.random.rand(2) #random numbers

In [ ]:
np.random.rand(2) #random numbers

In [ ]:
np.random.rand(2,3) #rand only float value will generate

In [ ]:
np.random.randint(2) #randint generate only integer value

`randint(2)` it will generate random integer between `0 to 2` (2 is excluded)

In [ ]:
np.random.randint(2,9)

In [ ]:
np.random.randint(2,9,4) # generate 4 numbers (9 is excluded)

In [ ]:
np.random.randint(10,40,(10,10))

In [ ]:
arr1 = np.random.randint(10,40,(10,10))

In [ ]:
arr1

In [ ]:
print(arr1)

In [ ]:
print(np.random.randint(10,40,(10,10)))

In [ ]:
arr1[2]

In [ ]:
arr1[-2]

In [ ]:
arr2 = np.random.randint(2,9,(5,7))
print(arr2)

In [ ]:
arr2[-3]

In [64]:
arr2[2:10]

array([[6, 8, 4, 5, 8, 7, 8],
       [3, 8, 6, 2, 3, 5, 8],
       [4, 4, 5, 5, 5, 4, 5]], dtype=int32)

In [65]:
arr2[:]

array([[6, 6, 5, 7, 6, 6, 5],
       [3, 2, 5, 6, 4, 8, 4],
       [6, 8, 4, 5, 8, 7, 8],
       [3, 8, 6, 2, 3, 5, 8],
       [4, 4, 5, 5, 5, 4, 5]], dtype=int32)

In [66]:
arr2[::-1]

array([[4, 4, 5, 5, 5, 4, 5],
       [3, 8, 6, 2, 3, 5, 8],
       [6, 8, 4, 5, 8, 7, 8],
       [3, 2, 5, 6, 4, 8, 4],
       [6, 6, 5, 7, 6, 6, 5]], dtype=int32)

In [67]:
arr2[3,4]

np.int32(3)

In [68]:
print(arr2[3,4])

3


In [69]:
arr2

array([[6, 6, 5, 7, 6, 6, 5],
       [3, 2, 5, 6, 4, 8, 4],
       [6, 8, 4, 5, 8, 7, 8],
       [3, 8, 6, 2, 3, 5, 8],
       [4, 4, 5, 5, 5, 4, 5]], dtype=int32)

In [70]:
arr2[0,1] = 10

In [71]:
arr2

array([[ 6, 10,  5,  7,  6,  6,  5],
       [ 3,  2,  5,  6,  4,  8,  4],
       [ 6,  8,  4,  5,  8,  7,  8],
       [ 3,  8,  6,  2,  3,  5,  8],
       [ 4,  4,  5,  5,  5,  4,  5]], dtype=int32)

In [72]:
arr2[:,0]

array([6, 3, 6, 3, 4], dtype=int32)

In [73]:
arr2[:, -3]

array([6, 4, 8, 3, 5], dtype=int32)

In [74]:
arr2[2:5, 2:5]

array([[4, 5, 8],
       [6, 2, 3],
       [5, 5, 5]], dtype=int32)

## Masking or Filter in numpy

In [75]:
arr2

array([[ 6, 10,  5,  7,  6,  6,  5],
       [ 3,  2,  5,  6,  4,  8,  4],
       [ 6,  8,  4,  5,  8,  7,  8],
       [ 3,  8,  6,  2,  3,  5,  8],
       [ 4,  4,  5,  5,  5,  4,  5]], dtype=int32)

In [76]:
arr2 > 5

array([[ True,  True, False,  True,  True,  True, False],
       [False, False, False,  True, False,  True, False],
       [ True,  True, False, False,  True,  True,  True],
       [False,  True,  True, False, False, False,  True],
       [False, False, False, False, False, False, False]])

In [77]:
arr2[arr2 > 5]

array([ 6, 10,  7,  6,  6,  6,  8,  6,  8,  8,  7,  8,  8,  6,  8],
      dtype=int32)

In [78]:
arr2[arr2 >= 5]

array([ 6, 10,  5,  7,  6,  6,  5,  5,  6,  8,  6,  8,  5,  8,  7,  8,  8,
        6,  5,  8,  5,  5,  5,  5], dtype=int32)

In [79]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [80]:
arr2[arr2 != 5]

array([ 6, 10,  7,  6,  6,  3,  2,  6,  4,  8,  4,  6,  8,  4,  8,  7,  8,
        3,  8,  6,  2,  3,  8,  4,  4,  4], dtype=int32)

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr.reshape(1, 7)

In [83]:
arr.reshape(7, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [84]:
arr.max()

np.int64(6)

In [85]:
arr.min()

np.int64(0)