# 1. Array creation Function

In [1]:
import numpy as np

In [2]:
# Create an array from a list
a = np.array([1, 2, 3])
print('Array a:', a)

Array a: [1 2 3]


In [3]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 2 4 6 8]


In [4]:
# Create an array filled with zeros
d = np.zeros((2, 3),)  # 2x3 array of zeros
print("Array d:\n", d) 

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Create an array filled with zeros
d = np.zeros((2, 3),dtype=int)  # 2x3 array of zeros
print("Array d:\n", d) 

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e) 

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
e = np.eye(4) #we can also use indentity instead of eye
print('Identity Matrix e:\n', e)

Identity Matrix e:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
e = np.eye(4, dtype=int)
print('Identity Matrix e:\n', e)

Identity Matrix e:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 2. Araay Manipulation Function

In [10]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [11]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (3, 1))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [12]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened) 

Flattened array: [1 2 3 4 5 6 7 8]


In [13]:
# transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print('Transposed array:\n', transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [14]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [[1 2]
 [3 4]]


In [15]:
a2 = np.array([1, 2])
b2 = np.array([3,4])
stacked = np.hstack([a2, b2])
print('Stacked arrays:\n', stacked)

Stacked arrays:
 [1 2 3 4]


# 3. Mathematical Function

In [16]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [17]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [18]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [19]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [20]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  # Dot product of a and g
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [21]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [22]:
a3 = np.array([1,2,3])
dot_product = np.dot(a, a1)
print('Dot product of a and a1:', dot_product)

Dot product of a and a1: 14


# 4. Statistical Function

In [23]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print('Mean of s:', mean)

Mean of s: 2.5


In [24]:
# Variance of an array
var = np.var(s)
print('Variance of s:', var)

Variance of s: 1.25


In [25]:
# Standard deviation of an array
std_dev = np.std(s)
print('Standard deviation of s:', std_dev)

Standard deviation of s: 1.118033988749895


In [26]:
s

array([1, 2, 3, 4])

In [27]:
# Minimum element of an array
minimum = np.min(s)
print('Min of s:', minimum)

Min of s: 1


In [28]:
# Maximum element of an array
maximum = np.max(s)
print('Max of s:', maximum)

Max of s: 4


# 5. Linear Algebra Function

In [29]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

# 6. Random Sampling Function

In [30]:
#Generate random values between 0 and 1
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print('Random values:', random_vals)

Random values: [0.13899577 0.58413918 0.05719935]


In [31]:
# Generate random integer
rand_ints = np.random.randint(0, 10, size=4)
print('Random integers:', rand_ints)

Random integers: [3 3 5 0]


In [32]:
# Set seed for reproductibility
np.random.seed(0)

rand_ints = np.random.randintrand_ints = np.random.randint(0, 10, size=5)
print('Random integers:', rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean and Logical Function

In [33]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [34]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [35]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


# 8. Set Operation

In [36]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [37]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [38]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 10. Other Functions

In [39]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [40]:
a

array([1, 2, 3])

In [41]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [42]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
