# NumPy

In [1]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers)

[10 20 30 40]


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
np.__version__

'2.4.6'

## 1. Python List to NumPy Array

In [4]:
numbers = [10, 20, 30, 40]

arr = np.array(numbers)

print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


### 1D Array

A one-dimensional array contains values in a single row.

In [5]:
arr = np.array([10, 20, 30, 40])

In [6]:
arr

array([10, 20, 30, 40])

### 2D Array

A two-dimensional array contains rows and columns.

In [7]:
arr = np.array([
    [10, 20],
    [30, 40]
])

print(arr)

[[10 20]
 [30 40]]


#### Python List

In [8]:
numbers = [10, 20, 30, 40]

result = []

for number in numbers:
    result.append(number + 5)

print(result)

[15, 25, 35, 45]


#### NumPy Array

In [9]:
numbers = np.array([10, 20, 30, 40, 50])
numbers = numbers + 5
print(numbers)

[15 25 35 45 55]


Here, NumPy performs the operation directly on all elements. This is called a **vectorized operation**.

## 2. Array Properties

| Property | Meaning |
|---|---|
| `ndim` | Number of dimensions |
| `shape` | Number of rows and columns |
| `size` | Total number of elements |
| `dtype` | Data type of elements |

In [11]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


## 3. Creating NumPy Arrays

### `np.array()`

In [12]:
arr = np.array([1, 2, 3, 4])

print(arr)

[1 2 3 4]


### `np.zeros()`

Creates an array filled with zeros.

In [13]:
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


### `np.ones()`

Creates an array filled with ones.

In [14]:
arr = np.ones(4)

print(arr)

[1. 1. 1. 1.]


### `np.full()`

Creates an array filled with a specified value.

In [21]:
arr = np.full(5, 10)
print(arr)

[10 10 10 10 10]


### `np.arange()`

- Creates values within a given range.

- `np.arange(start, stop, step)`

In [22]:
arr = np.arange(1, 6)

print(arr)

[1 2 3 4 5]


### `np.linspace()`

Creates a specified number of equally spaced values.

In [30]:
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


### `np.eye()`

Creates an identity matrix.

In [31]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 4. Array Indexing and Slicing

### 1D Indexing

In [32]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


In [33]:
arr = np.array([10, 20, 30, 40])

print(arr[-1])
print(arr[-2])

40
30


### 2D Indexing

For a 2D array, we use:

- `array[row, column]`

In [34]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr[0, 1])
print(arr[1, 2])

20
60


### Slicing

In [35]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


### 2D Slicing

In [36]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0:2, 1:3])

[[20 30]
 [50 60]]


## 5. Array Data Types

NumPy arrays have a data type called `dtype`.

In [37]:
arr = np.array([10, 20, 30])

print(arr.dtype)

int64


### Specifying Data Type

We can specify the data type while creating the array.

In [39]:
arr = np.array([10, 20, 30], dtype=float)

print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


### Changing Data Type Using `astype()`

In [40]:
arr = np.array([10, 20, 30])

new_arr = arr.astype(float)

print(new_arr)

[10. 20. 30.]


## 6. Array Operations

NumPy allows us to perform mathematical operations directly on arrays.

### Addition

In [41]:
arr = np.array([10, 20, 30])

print(arr + 5)

[15 25 35]


### Multiplication

In [42]:
arr = np.array([10, 20, 30])

print(arr * 2)

[20 40 60]


### Division

In [43]:
arr = np.array([10, 20, 30])

print(arr / 2)

[ 5. 10. 15.]


In [44]:
arr = np.array([10, 20, 30])

print(arr // 2)

[ 5 10 15]


### Operations Between Arrays

In [45]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


### Comparison Operations

In [46]:
arr = np.array([10, 20, 30, 40])

print(arr > 20)

[False False  True  True]


## 7. Broadcasting

Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

In [47]:
arr = np.array([10, 20, 30])

print(arr + 5)

[15 25 35]


In [50]:
a = np.array([10, 20, 30]) # 3 elements
b = np.array([1, 2, 3, 4]) # 4 elements

print(a + b) # both array must have same shape to perform operation
print(a * b)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [51]:
a = np.array([10, 20, 30]) # 3 elements
b = np.array([1, 2, 3]) # 3 elements

print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


## 8. Mathematical Functions

### Square Root

In [52]:
arr = np.array([4, 9, 16, 25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


### Absolute Value

In [53]:
arr = np.array([-10, 20, -30])

print(np.abs(arr))

[10 20 30]


### Rounding

In [54]:
arr = np.array([2.345, 5.678])

print(np.round(arr, 2))

[2.35 5.68]


### Power

In [55]:
arr = np.array([2, 3, 4])

print(np.power(arr, 2))

[ 4  9 16]


### Common Mathematical Functions

- `np.sqrt()`
- `np.abs()`
- `np.round()`
- `np.power()`
- `np.exp()`
- `np.log()`

## 9. Statistical and Aggregation Functions

NumPy provides functions to calculate common statistics.

### Common Statistical Functions

| Function | Purpose |
|---|---|
| `np.sum()` | Finds the total |
| `np.mean()` | Finds the average |
| `np.median()` | Finds the middle value |
| `np.min()` | Finds the smallest value |
| `np.max()` | Finds the largest value |
| `np.std()` | Finds standard deviation |
| `np.var()` | Finds variance |

In [56]:
marks = np.array([70, 80, 65, 90, 85])

print(np.sum(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.min(marks))
print(np.max(marks))
print(np.std(marks))
print(np.var(marks))

390
78.0
80.0
65
90
9.273618495495704
86.0


### `axis`

`axis` is useful when working with 2D arrays.

- `axis=0` → works column-wise
- `axis=1` → works row-wise

In [57]:
marks = np.array([
    [80, 70, 90],
    [60, 85, 75]
])

print(np.sum(marks, axis=0))
print(np.sum(marks, axis=1))

[140 155 165]
[240 220]


## 10. Boolean Indexing, Masking and Filtering

Boolean indexing is used to select elements based on a condition.

In [58]:
marks = np.array([45, 67, 89, 32, 76])

print(marks >= 50)

[False  True  True False  True]


The Boolean array is called a **Boolean mask**.

We can use this mask to filter values:

In [59]:
marks = np.array([45, 67, 89, 32, 76])

result = marks[marks >= 50]

print(result)

[67 89 76]


### Multiple Conditions

In [60]:
marks = np.array([45, 67, 89, 32, 76])

result = marks[(marks >= 50) & (marks <= 80)]

print(result)

[67 76]


## 11. `np.where()`

`np.where()` is used to select values or find positions based on a condition.

### Find Positions

In [61]:
marks = np.array([40, 65, 80, 35])

print(np.where(marks >= 50))

(array([1, 2]),)


The positions `1` and `2` contain values greater than or equal to `50`.

### Select Values

`np.where()` can also select one value when the condition is true and another value when it is false.

In [62]:
marks = np.array([40, 65, 80, 35])

result = np.where(marks >= 50, "Pass", "Fail")

print(result)

['Fail' 'Pass' 'Pass' 'Fail']


## 12. Array Manipulation

Array manipulation means changing the structure or form of an array.

In [63]:
arr = np.arange(1, 7)

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


### `flatten()`

Converts a multidimensional array into a 1D array.

In [64]:
arr = np.array([
    [1, 2],
    [3, 4]
])

print(arr.flatten())

[1 2 3 4]


### `ravel()`

Also converts an array into a 1D form.

In [65]:
print(arr.ravel())

[1 2 3 4]


### Transpose

Transpose changes rows into columns and columns into rows.

In [66]:
print(arr.T)

[[1 3]
 [2 4]]


## 13. Joining and Splitting Arrays

### `np.concatenate()`

Joins arrays together.

In [68]:
a = np.array([1, 2])
b = np.array([3, 4])

result = np.concatenate((a, b))

print(result)

[1 2 3 4]


### Other Joining Functions

* `np.concatenate()` – Used to join arrays along an existing axis.
* `np.stack()` – Used to join arrays along a **new axis**.
* `np.hstack()` – Used to join arrays **horizontally (column-wise)**.
* `np.vstack()` – Used to join arrays **vertically (row-wise)**.

### `np.split()`

Splits an array into multiple parts.

In [70]:
arr = np.array([1, 2, 3, 4])

result = np.split(arr, 2)

print(result)

[array([1, 2]), array([3, 4])]


## 14. Sorting and Searching

### `np.sort()`

Sorts an array.

In [71]:
arr = np.array([40, 10, 30, 20])

print(np.sort(arr))

[10 20 30 40]


### `np.argsort()`

Returns the indexes that would sort the array.

In [72]:
arr = np.array([40, 10, 30, 20])

print(np.argsort(arr))

[1 3 2 0]


### `np.unique()`

Finds unique values

In [73]:
arr = np.array([10, 20, 10, 30, 20])

print(np.unique(arr))

[10 20 30]


### `np.searchsorted()`

Finds the position where a value can be inserted while keeping the array sorted.

In [74]:
arr = np.array([10, 20, 30, 40])

print(np.searchsorted(arr, 25))

2


## 15. Random Numbers and Sampling

NumPy provides functions for generating random values.

### Random Seed

A seed is used when we want the same random results every time.

In [84]:
np.random.seed(10)

print(np.random.randint(1, 10, 5))

[5 1 2 1 2]


### `np.random.seed()`

- `seed()` fixes the starting point of random number generation so that the same sequence of random numbers can be generated again.

- `np.random.seed()` is used to get reproducible random results; using the same seed value produces the same sequence of random numbers.

### `np.random.rand()`

Generates random floating-point numbers between `0` and `1`.

In [80]:
np.random.seed(10)

print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]


### `np.random.randint()`

Generates random integers.

In [82]:
np.random.seed(10)

print(np.random.randint(1, 10, 5))

[5 1 2 1 2]


### `np.random.choice()`

Selects random values from an array.

In [83]:
np.random.seed(10)

arr = np.array([10, 20, 30, 40, 50])

print(np.random.choice(arr, 3))

[20 50 10]


## 16. Linear Algebra

NumPy provides functions for matrix and linear algebra operations.

### Matrix Multiplication

In [85]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.matmul(a, b)

print(result)

[[19 22]
 [43 50]]


### Dot Product

In [86]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)

print(result)

32


### Other Linear Algebra Operations

* **Matrix transpose** – `np.transpose()`
* **Matrix inverse** – `np.linalg.inv()`
* **Determinant** – `np.linalg.det()`
* **Eigenvalues** – `np.linalg.eigvals()`
* **Eigenvectors** – `np.linalg.eig()`

## 17. Logical and Boolean Functions

NumPy provides functions for checking and combining conditions.

### `np.all()`

Checks whether all values satisfy a condition.

In [87]:
arr = np.array([10, 20, 30])

print(np.all(arr > 0))

True


### `np.any()`

Checks whether at least one value satisfies a condition.

In [88]:
arr = np.array([10, 20, 30])

print(np.any(arr > 25))

True


### `np.logical_and()`

Performs logical AND between two Boolean arrays.

In [89]:
a = np.array([True, True, False])
b = np.array([True, False, True])

print(np.logical_and(a, b))

[ True False False]


### Other Logical Functions

- `np.logical_and()`
- `np.logical_or()`
- `np.logical_not()`

## 18. Set Operations

NumPy provides functions for performing set-like operations on arrays.

In [90]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

### Union

Returns all unique values from both arrays.

In [91]:
print(np.union1d(a, b))

[1 2 3 4 5 6]


### Intersection

Returns values that are present in both arrays.

In [92]:
print(np.intersect1d(a, b))

[3 4]


### Difference

Returns values that are present in the first array but not in the second array.

In [93]:
print(np.setdiff1d(a, b))

[1 2]


## 19. Handling Missing and Special Values

NumPy provides special values such as `np.nan` and `np.inf`.

### `np.nan`

`np.nan` represents a missing or undefined numerical value.

In [94]:
arr = np.array([10, 20, np.nan, 40])

print(np.isnan(arr))

[False False  True False]


### `np.inf`

`np.inf` represents infinity.

In [95]:
arr = np.array([10, np.inf, 30])

print(arr)

[10. inf 30.]


### `np.isfinite()`

Checks whether values are finite.

In [96]:
arr = np.array([10, np.nan, np.inf, 40])

print(np.isfinite(arr))

[ True False False  True]


### Common Functions

* `np.isnan()` – Used to **check for NaN (Not a Number) values**.
* `np.isinf()` – Used to **check for infinite (`∞` or `-∞`) values**.
* `np.isfinite()` – Used to **check whether values are finite (not NaN or infinity)**.

## 20. Copy and View

NumPy arrays can be copied or viewed.

### Copy

A copy creates a separate array. Changes made to the copy do not affect the original array.

In [97]:
arr = np.array([10, 20, 30])

copy_arr = arr.copy()

copy_arr[0] = 100

print(arr)
print(copy_arr)

[10 20 30]
[100  20  30]


### View

A view shares the same underlying data. Changes made to the view can affect the original array.

In [98]:
arr = np.array([10, 20, 30])

view_arr = arr.view()

view_arr[0] = 100

print(arr)
print(view_arr)

[100  20  30]
[100  20  30]


### Difference

| Copy | View |
|---|---|
| Creates a separate array | Shares data with the original |
| Changes do not affect the original | Changes can affect the original |
| Uses separate memory | Shares underlying data |

## 21. Parameters and Hyperparameters tuning

### Parameters

When NumPy uses the default data type automatically.

In [100]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.dtype)

int64


### Hyperparameters

When the user explicitly changes the data type using the `dtype` parameter.

In [101]:
import numpy as np

arr = np.array([10, 20, 30], dtype=float)

print(arr.dtype)

float64
