In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.6'

In [4]:
my_list = [0, 1, 2, 3, 4, 5, 6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [5]:
type(my_list)

list

# List to array

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(5, 100, 10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [12]:
np.arange(20,10)

array([], dtype=int64)

In [13]:
np.arange(20, 10, -1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [14]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

## Parameter tuning

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Hyper parameter tuning

In [16]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.zeros((10,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [27]:
rand(2,3)

NameError: name 'rand' is not defined

In [28]:
np.random.rand(2) #random numbers

array([0.26974735, 0.25511118])

In [29]:
np.random.rand(2) #random numbers

array([0.48723543, 0.97453555])

In [30]:
np.random.rand(2,3) #rand only float value will generate

array([[0.67900253, 0.26123996, 0.76459573],
       [0.01132559, 0.21327649, 0.02281599]])

In [39]:
np.random.randint(2) #randint generate only integer value

1

`randint(2)` it will generate random integer between `0 to 2` (2 is excluded)

In [44]:
np.random.randint(2,9)

4

In [46]:
np.random.randint(2,9,4) # generate 4 numbers (9 is excluded)

array([7, 7, 6, 6], dtype=int32)

In [49]:
np.random.randint(10,40,(10,10))

array([[33, 32, 15, 30, 20, 23, 34, 30, 25, 19],
       [32, 11, 33, 12, 23, 18, 14, 26, 31, 17],
       [26, 15, 14, 13, 10, 23, 31, 22, 23, 13],
       [38, 14, 31, 12, 29, 30, 24, 11, 10, 10],
       [33, 20, 36, 22, 27, 31, 16, 23, 14, 32],
       [17, 29, 16, 11, 17, 22, 35, 38, 32, 15],
       [26, 38, 32, 13, 30, 33, 22, 12, 16, 26],
       [17, 16, 31, 29, 19, 17, 34, 38, 13, 10],
       [34, 15, 16, 32, 25, 16, 39, 29, 24, 22],
       [39, 30, 17, 25, 12, 27, 19, 19, 18, 10]], dtype=int32)

In [50]:
arr1 = np.random.randint(10,40,(10,10))

In [53]:
arr1

array([[23, 31, 13, 28, 19, 38, 24, 19, 38, 31],
       [28, 16, 33, 29, 25, 14, 32, 20, 30, 39],
       [34, 39, 10, 33, 27, 32, 24, 12, 14, 12],
       [30, 28, 34, 17, 15, 35, 14, 10, 26, 28],
       [18, 24, 27, 15, 28, 15, 28, 28, 14, 35],
       [19, 15, 18, 23, 39, 24, 16, 35, 24, 24],
       [22, 30, 33, 27, 28, 35, 23, 27, 13, 36],
       [31, 39, 39, 14, 25, 34, 24, 39, 39, 21],
       [36, 18, 19, 31, 38, 35, 33, 31, 23, 28],
       [11, 32, 10, 28, 30, 10, 35, 10, 33, 22]], dtype=int32)

In [52]:
print(arr1)

[[23 31 13 28 19 38 24 19 38 31]
 [28 16 33 29 25 14 32 20 30 39]
 [34 39 10 33 27 32 24 12 14 12]
 [30 28 34 17 15 35 14 10 26 28]
 [18 24 27 15 28 15 28 28 14 35]
 [19 15 18 23 39 24 16 35 24 24]
 [22 30 33 27 28 35 23 27 13 36]
 [31 39 39 14 25 34 24 39 39 21]
 [36 18 19 31 38 35 33 31 23 28]
 [11 32 10 28 30 10 35 10 33 22]]


In [54]:
print(np.random.randint(10,40,(10,10)))

[[14 27 23 36 13 15 10 21 13 20]
 [11 37 11 33 14 31 21 20 11 19]
 [16 30 26 11 30 17 30 14 22 14]
 [21 13 11 21 21 32 39 15 33 30]
 [13 25 24 39 19 20 17 36 37 35]
 [18 14 14 23 15 16 14 12 38 35]
 [31 31 37 10 13 39 14 31 23 21]
 [34 32 24 32 11 10 19 11 20 19]
 [18 30 24 38 27 25 26 37 14 30]
 [12 31 11 15 21 34 22 29 24 27]]


In [59]:
arr1[2]

array([34, 39, 10, 33, 27, 32, 24, 12, 14, 12], dtype=int32)

In [61]:
arr1[-2]

array([36, 18, 19, 31, 38, 35, 33, 31, 23, 28], dtype=int32)

In [62]:
arr2 = np.random.randint(2,9,(5,7))
print(arr2)

[[6 6 5 7 6 6 5]
 [3 2 5 6 4 8 4]
 [6 8 4 5 8 7 8]
 [3 8 6 2 3 5 8]
 [4 4 5 5 5 4 5]]


In [63]:
arr2[-3]

array([6, 8, 4, 5, 8, 7, 8], dtype=int32)

In [64]:
arr2[2:10]

array([[6, 8, 4, 5, 8, 7, 8],
       [3, 8, 6, 2, 3, 5, 8],
       [4, 4, 5, 5, 5, 4, 5]], dtype=int32)

In [65]:
arr2[:]

array([[6, 6, 5, 7, 6, 6, 5],
       [3, 2, 5, 6, 4, 8, 4],
       [6, 8, 4, 5, 8, 7, 8],
       [3, 8, 6, 2, 3, 5, 8],
       [4, 4, 5, 5, 5, 4, 5]], dtype=int32)

In [66]:
arr2[::-1]

array([[4, 4, 5, 5, 5, 4, 5],
       [3, 8, 6, 2, 3, 5, 8],
       [6, 8, 4, 5, 8, 7, 8],
       [3, 2, 5, 6, 4, 8, 4],
       [6, 6, 5, 7, 6, 6, 5]], dtype=int32)

In [67]:
arr2[3,4]

np.int32(3)

In [68]:
print(arr2[3,4])

3


In [69]:
arr2

array([[6, 6, 5, 7, 6, 6, 5],
       [3, 2, 5, 6, 4, 8, 4],
       [6, 8, 4, 5, 8, 7, 8],
       [3, 8, 6, 2, 3, 5, 8],
       [4, 4, 5, 5, 5, 4, 5]], dtype=int32)

In [70]:
arr2[0,1] = 10

In [71]:
arr2

array([[ 6, 10,  5,  7,  6,  6,  5],
       [ 3,  2,  5,  6,  4,  8,  4],
       [ 6,  8,  4,  5,  8,  7,  8],
       [ 3,  8,  6,  2,  3,  5,  8],
       [ 4,  4,  5,  5,  5,  4,  5]], dtype=int32)

In [72]:
arr2[:,0]

array([6, 3, 6, 3, 4], dtype=int32)

In [73]:
arr2[:, -3]

array([6, 4, 8, 3, 5], dtype=int32)

In [74]:
arr2[2:5, 2:5]

array([[4, 5, 8],
       [6, 2, 3],
       [5, 5, 5]], dtype=int32)

## Masking or Filter in numpy

In [75]:
arr2

array([[ 6, 10,  5,  7,  6,  6,  5],
       [ 3,  2,  5,  6,  4,  8,  4],
       [ 6,  8,  4,  5,  8,  7,  8],
       [ 3,  8,  6,  2,  3,  5,  8],
       [ 4,  4,  5,  5,  5,  4,  5]], dtype=int32)

In [76]:
arr2 > 5

array([[ True,  True, False,  True,  True,  True, False],
       [False, False, False,  True, False,  True, False],
       [ True,  True, False, False,  True,  True,  True],
       [False,  True,  True, False, False, False,  True],
       [False, False, False, False, False, False, False]])

In [77]:
arr2[arr2 > 5]

array([ 6, 10,  7,  6,  6,  6,  8,  6,  8,  8,  7,  8,  8,  6,  8],
      dtype=int32)

In [78]:
arr2[arr2 >= 5]

array([ 6, 10,  5,  7,  6,  6,  5,  5,  6,  8,  6,  8,  5,  8,  7,  8,  8,
        6,  5,  8,  5,  5,  5,  5], dtype=int32)

In [79]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [80]:
arr2[arr2 != 5]

array([ 6, 10,  7,  6,  6,  3,  2,  6,  4,  8,  4,  6,  8,  4,  8,  7,  8,
        3,  8,  6,  2,  3,  8,  4,  4,  4], dtype=int32)

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [82]:
arr.reshape(2,3)

ValueError: cannot reshape array of size 7 into shape (2,3)

In [83]:
arr.reshape(7, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [84]:
arr.max()

np.int64(6)

In [85]:
arr.min()

np.int64(0)