# Linear Algebra

This notebook provides practical calculations for vectors, matrices, matrix multiplication, systems of equations, determinants, inverses, rank, eigenvalues, and SVD.


## 1. Learning Goals

- Create vectors and matrices with NumPy.
- Perform vector arithmetic and dot products.
- Calculate norms and distances.
- Perform matrix operations.
- Solve linear systems.
- Calculate determinants and inverses.
- Find rank, eigenvalues, eigenvectors, and SVD.


In [1]:
import numpy as np


## 2. Vectors


In [2]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("a:", a)
print("b:", b)
print("a + b:", a + b)
print("a - b:", a - b)
print("3a:", 3 * a)


a: [2 4 6]
b: [1 3 5]
a + b: [ 3  7 11]
a - b: [1 1 1]
3a: [ 6 12 18]


## 3. Dot Product


In [3]:
dot_product = np.dot(a, b)
print("Dot product:", dot_product)


Dot product: 44


## 4. Norm and Unit Vector


In [4]:
x = np.array([3, 4], dtype=float)

norm = np.linalg.norm(x)
unit_vector = x / norm

print("Norm:", norm)
print("Unit vector:", unit_vector)
print("Unit-vector norm:", np.linalg.norm(unit_vector))


Norm: 5.0
Unit vector: [0.6 0.8]
Unit-vector norm: 1.0


## 5. Euclidean Distance


In [5]:
p = np.array([3, 4])
q = np.array([1, 1])

distance = np.linalg.norm(p - q)
print("Distance:", distance)


Distance: 3.605551275463989


## 6. Matrices and Shapes


In [6]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A:\n", A)
print("Shape of A:", A.shape)


A:
 [[1 2]
 [3 4]]
Shape of A: (2, 2)


## 7. Matrix Addition and Subtraction


In [7]:
print("A + B:\n", A + B)
print("A - B:\n", A - B)


A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]


## 8. Scalar Multiplication


In [8]:
print("3A:\n", 3 * A)


3A:
 [[ 3  6]
 [ 9 12]]


## 9. Matrix Multiplication


In [9]:
print("A @ B:\n", A @ B)
print("Element-wise A * B:\n", A * B)


A @ B:
 [[19 22]
 [43 50]]
Element-wise A * B:
 [[ 5 12]
 [21 32]]


## 10. Transpose


In [10]:
print("A transpose:\n", A.T)


A transpose:
 [[1 3]
 [2 4]]


## 11. Determinant


In [11]:
det_A = np.linalg.det(A)
print("det(A):", det_A)


det(A): -2.0000000000000004


## 12. Matrix Inverse


In [12]:
A_inv = np.linalg.inv(A)

print("A inverse:\n", A_inv)
print("A @ A_inverse:\n", A @ A_inv)


A inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inverse:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 13. Solve a Linear System

Solve:

$$
2x+y=5
$$

$$
x-y=1
$$


In [13]:
A_system = np.array([
    [2, 1],
    [1, -1]
], dtype=float)

b_system = np.array([5, 1], dtype=float)

solution = np.linalg.solve(A_system, b_system)
print("Solution:", solution)


Solution: [2. 1.]


## 14. Rank


In [14]:
rank_matrix = np.array([
    [1, 2],
    [2, 4]
], dtype=float)

print("Rank:", np.linalg.matrix_rank(rank_matrix))


Rank: 1


## 15. Null Space Exercise

For a small matrix, verify a candidate null-space vector by checking:

$$
A\mathbf{x}=\mathbf{0}
$$


In [15]:
N = np.array([
    [1, 2],
    [2, 4]
], dtype=float)

v = np.array([-2, 1], dtype=float)
print("N @ v:", N @ v)


N @ v: [0. 0.]


## 16. Orthogonality


In [16]:
u = np.array([1, 2])
v = np.array([2, -1])

print("Dot product:", np.dot(u, v))


Dot product: 0


## 17. Projection


In [17]:
x = np.array([3, 4], dtype=float)
u = np.array([1, 0], dtype=float)

projection = (np.dot(x, u) / np.dot(u, u)) * u
print("Projection:", projection)
print("Orthogonal remainder:", x - projection)
print("Remainder dot u:", np.dot(x - projection, u))


Projection: [3. 0.]
Orthogonal remainder: [0. 4.]
Remainder dot u: 0.0


## 18. Eigenvalues and Eigenvectors


In [18]:
E = np.array([
    [2, 0],
    [0, 3]
], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(E)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


## 19. Verify an Eigenpair


In [19]:
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    vec = eigenvectors[:, i]
    print("Eigenvalue:", lam)
    print("A v:", E @ vec)
    print("lambda v:", lam * vec)
    print()


Eigenvalue: 2.0
A v: [2. 0.]
lambda v: [2. 0.]

Eigenvalue: 3.0
A v: [0. 3.]
lambda v: [0. 3.]



## 20. Singular Value Decomposition


In [20]:
M = np.array([
    [1, 2],
    [3, 4]
], dtype=float)

U, S, VT = np.linalg.svd(M)

Sigma = np.zeros_like(M)
np.fill_diagonal(Sigma, S)

reconstructed = U @ Sigma @ VT

print("U:\n", U)
print("Singular values:", S)
print("V^T:\n", VT)
print("Reconstructed matrix:\n", reconstructed)


U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V^T:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Reconstructed matrix:
 [[1. 2.]
 [3. 4.]]


## 21. Frobenius Norm


In [21]:
frobenius_norm = np.linalg.norm(M, ord="fro")
print("Frobenius norm:", frobenius_norm)


Frobenius norm: 5.477225575051661


## 22. Practice Questions

1. Create two three-dimensional vectors and calculate their sum and difference.
2. Calculate the dot product manually and verify it with NumPy.
3. Calculate the Euclidean norm of a vector.
4. Convert a non-zero vector into a unit vector.
5. Create two matrices with compatible dimensions and calculate their product.
6. Create two matrices with incompatible dimensions and explain why multiplication fails.
7. Calculate a $2\times2$ determinant manually and verify it with NumPy.
8. Solve a system of three linear equations using `np.linalg.solve()`.
9. Create a rank-deficient matrix and calculate its rank.
10. Find eigenvalues and eigenvectors of a diagonal matrix.
11. Verify an eigenpair numerically.
12. Calculate the SVD of a rectangular matrix and reconstruct it.
13. Calculate a matrix's Frobenius norm manually and with NumPy.
14. Find two orthogonal vectors and verify their dot product is zero.
15. Calculate the projection of one vector onto another.


## 23. Final Practical Checklist

- Check vector and matrix shapes before operations.
- Distinguish `*` from `@` in NumPy.
- Use `.T` for transpose.
- Use `np.linalg.solve()` for linear systems when appropriate.
- Check the determinant before discussing a square matrix inverse.
- Use `np.linalg.matrix_rank()` to inspect rank.
- Verify eigenpairs using $A\mathbf{v}=\lambda\mathbf{v}$.
- Verify SVD reconstruction using $A\approx U\Sigma V^T$.
- Do not confuse a vector norm with a matrix determinant.
